
pipeline {
    agent { label 'gradle'}
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                credentialsId: 'Jenkins-lab',
                url: 'https://github.com/raullopezpenalva/bootcamp-devops-lemoncode.git'
            }
        }
        stage('Compile') {
            steps {
                dir('03-cd/exercises/jenkins-resources/calculator') {
                    sh './gradlew compileJava'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                dir('03-cd/exercises/jenkins-resources/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }
}